def shared_pods
    pod 'UserDefaultsStore'
end

target 'Adventures' do
  platform :watchos, '2.0'
  shared_pods
end

target 'Adventures WatchKit App' do
  platform :watchos, '2.0'
  shared_pods
end

target 'Adventures WatchKit Extension' do
 platform :watchos, '2.0'
 shared_pods
end
